"""First revision

Revision ID: 8bdea1b48f5d
Revises: 
Create Date: 2024-06-13 08:27:24.974225

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import LocaleType


# revision identifiers, used by Alembic.
revision = "8bdea1b48f5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creator",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("locale", LocaleType(), nullable=True),
        sa.Column("totp_secret", sa.String(), nullable=True),
        sa.Column("totp_counter", sa.Integer(), nullable=True),
        sa.Column("email_validated", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("is_moderator", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_creator_email"), "creator", ["email"], unique=True)
    op.create_index(op.f("ix_creator_id"), "creator", ["id"], unique=False)
    op.create_table(
        "token",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("scopes", sa.String(), nullable=True),
        sa.Column("authenticates_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["authenticates_id"],
            ["creator.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(op.f("ix_token_token"), "token", ["token"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_token"), table_name="token")
    op.drop_table("token")
    op.drop_index(op.f("ix_creator_id"), table_name="creator")
    op.drop_index(op.f("ix_creator_email"), table_name="creator")
    op.drop_table("creator")
    # ### end Alembic commands ###
